### ISSUE TITLE
Could you add the repo name?

### ISSUE THREAD

**Issue by Davidslv** [emmabeynon/github-trello-poster#36]
Hello,

There are some tasks that require us to go and do some repetitive work, which might mean that the title for the PR is identical, could you add the repo name before the PR title?

Example:
![screen shot 2016-11-25 at 13 02 20](https://cloud.githubusercontent.com/assets/136777/20626117/6f56b746-b30f-11e6-8b17-eaa1bb7a204a.png)

Suggestion:

`[REPO NAME] PR TITLE`

Thank you,
David

**Comment by emmabeynon** [comment]
It looks like Trello has since updated how it displays links to PRs now so that by default it displays the repo name, so we don't need to support this:

<img width="570" alt="screen shot 2018-06-27 at 14 44 14" src="https://user-images.githubusercontent.com/13434452/41977978-adc97bcc-7a18-11e8-8c4a-f4b77d69f074.png">
